import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { UserContextProvider } from "@/lib/userContext";

const inter = Inter({ subsets: ["latin"] });

const RouterOption = ({ name, url }: { name: string; url: string }) => {
  return (
    <Link
      className="border-1 border-solid border-white m-10 p-5 cursor-pointer"
      href={url}
    >
      {name}
    </Link>
  );
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <div className="flex">
            <RouterOption name={"Home"} url={"./"} />
            <RouterOption name={"Login"} url={"./login"} />
            <RouterOption name={"Event"} url={"./event"} />
          </div>
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
